[package]
name = "amidir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alsa = "0.7.0"
clap = { version = "4.2.2", features = ["derive"] }
libc = "0.2.141"
